spring.application.name=chavo
spring.datasource.url=jdbc:postgresql://localhost:5432/mudanzasdb
spring.datasource.username=admin
spring.datasource.password=9533
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE